### ISSUE TITLE
[BUG] [2.1-SNAPSHOT] There is a certain chance of java.lang.IllegalArgumentException: Invalid identifier

### ISSUE THREAD

**Issue by XiaoPangxie732** [MaxPixelStudios/MinecraftDecompiler#12]
**Describe the bug**
When -r is enabled, there is a certain chance of producing java.lang.IllegalArgumentException: Invalid identifier  
But it should not happen in theory

**To Reproduce**
1. Pass args '-r' and required args
2. Might see error in a certain chance

**System Info:**
 - OS: Windows 10
 - Arch: x64
 - Java: AdoptOpenJDK jdk8u242-b08
 - MinecraftDecompiler Version: 2.1-SNAPSHOT

**Comment by XiaoPangxie732** [comment]
I can't fix this issue, so I need your help. :)

**Comment by XiaoPangxie732** [comment]
```
[2021-02-19 00:32:31] [AbstractDeobfuscator] [cn.maxpixel.mcdecompiler.deobfuscator.AbstractDeobfuscator] [ERROR] Error when remapping classes or coping files
 java.lang.IllegalArgumentException: Invalid identifier
	at cn.maxpixel.mcdecompiler.util.IntLocal.check(IntLocal.java:43) ~[classes/:?]
	at cn.maxpixel.mcdecompiler.util.IntLocal.get(IntLocal.java:50) ~[classes/:?]
	at cn.maxpixel.mcdecompiler.asm.JADNameGenerator$LVTRenamer.getVarName(JADNameGenerator.java:89) ~[classes/:?]
	at cn.maxpixel.mcdecompiler.asm.JADNameGenerator$LVTRenamer.visitLocalVariable(JADNameGenerator.java:108) ~[classes/:?]
	at org.objectweb.asm.MethodVisitor.visitLocalVariable(MethodVisitor.java:708) ~[asm-9.1.jar:9.1]
	at org.objectweb.asm.commons.MethodRemapper.visitLocalVariable(MethodRemapper.java:240) ~[asm-commons-9.1.jar:9.1]
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2571) ~[asm-9.1.jar:9.1]
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491) ~[asm-9.1.jar:9.1]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:721) ~[asm-9.1.jar:9.1]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401) ~[asm-9.1.jar:9.1]
	at cn.maxpixel.mcdecompiler.deobfuscator.AbstractDeobfuscator.lambda$sharedDeobfuscate$3(AbstractDeobfuscator.java:87) ~[classes/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) [?:1.8.0_242]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_242]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_242]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_242]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) [?:1.8.0_242]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:313) [?:1.8.0_242]
	at java.util.stream.StreamSpliterators$UnorderedSliceSpliterator$OfRef.forEachRemaining(StreamSpliterators.java:1050) [?:1.8.0_242]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) [?:1.8.0_242]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_242]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_242]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_242]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_242]
```
