### ISSUE TITLE
Cannot decompile latest snapshots

### ISSUE THREAD

**Issue by White-145** [MaxPixelStudios/MinecraftDecompiler#139]
**Description**:
When trying to decompile minecraft version 24w14a and later error is outputted

**Steps to reproduce the behavior**:
1. Pass args '--version 24w14a --side CLIENT --output dir\24w14a.zip'
2. See error

**Expected behaviour**:
Version is downloaded and decompiled, without any errors.

**Logs**:
```
C:\Users\User\Desktop\MinecraftDecompiler>java -jar MinecraftDecompiler.jar --version 24w14a --side CLIENT --output dir\24w14a-client.zip
[2024-04-15T21:11:51.3271352] [ClassifiedDeobfuscator] [INFO] [cn.maxpixel.mcdecompiler.ClassifiedDeobfuscator/deobfuscate] Deobfuscating...
Exception in thread "main" java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Unsupported class file major version 65
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:172)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:992)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:964)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2386)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2328)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:172)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:992)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:964)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2386)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2328)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:172)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:992)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:964)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2386)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2328)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:172)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:992)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:964)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2386)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2328)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540)[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:172)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:992)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:964)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2341)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:172)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:992)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:964)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2386)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2328)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:172)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:992)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:964)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2386)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2328)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.io.EOFException: Unexpected end of ZLIB input stream
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2275)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.io.EOFException: Unexpected end of ZLIB input stream
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2275)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


[2024-04-15T21:11:51.4011265] [Class Info Collector] [WARNING] [cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation/accept] Error when creating super class mapping
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:172)
        at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:992)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:964)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1241)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:1236)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.initDataPos(ZipFileSystem.java:2386)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryInputStream.read(ZipFileSystem.java:2328)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$2.fill(ZipFileSystem.java:2278)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
        at cn.maxpixel.mcdecompiler.util.IOUtil.readAllBytes(IOUtil.java:49)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.<init>(ExtraClassesInformation.java:47)
        at cn.maxpixel.mcdecompiler.ClassifiedDeobfuscator.deobfuscate(ClassifiedDeobfuscator.java:122)
        at cn.maxpixel.mcdecompiler.MinecraftDecompiler.deobfuscate(MinecraftDecompiler.java:81)
        at cn.maxpixel.mcdecompiler.MinecraftDecompilerCommandLine.main(MinecraftDecompilerCommandLine.java:124)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:54)
        at cn.maxpixel.mcdecompiler.asm.ExtraClassesInformation.accept(ExtraClassesInformation.java:34)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at cn.maxpixel.mcdecompiler.util.FileUtil.lambda$iterateFiles$0(FileUtil.java:138)
        at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:450)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**System Info:**
 - OS: Windows 10
 - Arch: x64
 - Java: OracleJDK 21.0.2
 - MinecraftDecompiler Version 3.2

**Comment by XiaoPangxie732** [comment]
Use 3.3.2

**Comment by XiaoPangxie732** [comment]
https://github.com/MaxPixelStudios/MinecraftDecompiler/tree/v3.3.2

**Comment by XiaoPangxie732** [comment]
https://github.com/MaxPixelStudios/MinecraftDecompiler/releases/tag/v3.3.2

**Comment by White-145** [comment]
Ah ok, thank you
