### ISSUE TITLE
[BUG] Decomplication failure that can't be fixed

### ISSUE THREAD

**Issue by novastosha** [MaxPixelStudios/MinecraftDecompiler#28]
I am trying to decompile minecraft version 1.17.1 and I am executing the JAR file with the arguments:

--d CFR --input "./1.17.1.jar" --mappingPath "./clientmappings.txt" --outputDecomp "./output/"

Every file exists except for "deobfuscated.jar" that should be generated by the code it self.

But your code thinks that this file does not exist so I am getting this exception and the decomplication fails:

←[m←[31m[2021-12-05 14:50:34] [MinecraftDecompiler] [cn.maxpixel.mcdecompiler.MinecraftDecompiler] [FATAL] Error when decompiling
←[m java.nio.file.NoSuchFileException: C:\Users\novastosha\Application Data\Desktop\ZodaClient Preperations\output\deobfuscated.jar
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsLinkSupport.getFinalPath(WindowsLinkSupport.java:74) ~[?:?]
        at sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:241) ~[?:?]
        at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:933) ~[?:?]
        at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:42) ~[?:?]
        at jdk.nio.zipfs.ZipFileSystemProvider.lambda$removeFileSystem$0(ZipFileSystemProvider.java:305) ~[jdk.zipfs:?]
        at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
        at jdk.nio.zipfs.ZipFileSystemProvider.removeFileSystem(ZipFileSystemProvider.java:307) ~[jdk.zipfs:?]
        at jdk.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:521) ~[jdk.zipfs:?]
        at cn.maxpixel.mcdecompiler.MinecraftDecompiler.decompile0(MinecraftDecompiler.java:145) [MinecraftDecompiler.jar:2.4]
        at cn.maxpixel.mcdecompiler.MinecraftDecompiler.decompile(MinecraftDecompiler.java:111) [MinecraftDecompiler.jar:2.4]
        at cn.maxpixel.mcdecompiler.MinecraftDecompilerCommandLine.main(MinecraftDecompilerCommandLine.java:141) [MinecraftDecompiler.jar:2.4]

Help is appreciated.

**Comment by XiaoPangxie732** [comment]
Apologize for my late response.

The default output directory of the deobfuscated jar is `output`. MinecraftDecompiler will delete then recreate the directory of decompiled output to make sure the decompiled output is "clean". If the directory of decompiled output is the same as the output directory of the deobfuscated jar, the deobfuscated jar will be deleted and produce the error above.

I'm not a native English speaker. If some words I said are confusing you, I am sorry.

**Comment by XiaoPangxie732** [comment]
I'll write a check later to ensure the value of `--output` and `--outputDecomp` is different

**Comment by XiaoPangxie732** [comment]
btw, you can use simpler arguments like `-v 1.17.1 -s CLIENT -d CFR` if you use official mappings to deobfuscate and decompile

**Comment by novastosha** [comment]
Excuse me for the late reply, I realised that so I changed and if you can add a check for the values of output and decompile output are different because that confused me for hella long time...
