### ISSUE TITLE
[BUG] [2.5] The decompiler is weird and none of them work.

### ISSUE THREAD

**Issue by novastosha** [MaxPixelStudios/MinecraftDecompiler#34]
Decompiler was ran using the following arguments:

--output ./outMap --d SPIGOT --outputDecomp ./outDecomp --side CLIENT --version 1.17.1

All the decompilers don't work and many of them produce unknown characters. and when using the "--rvn" option, referencing the the class it self using "this" doesn't work, what I mean by doesn't work here is that it does not use "this" at all.

I hope you get better decompilers added very soon.

Example of output code, this piece is found on the constructor of "net.minecraft.client.server.IntegratedServer"
  ```java 
  super(â˜ƒ, â˜ƒ, â˜ƒ, â˜ƒ, â˜ƒ, â˜ƒ.getProxy(), â˜ƒ.getFixerUpper(), â˜ƒ, â˜ƒ, â˜ƒ, â˜ƒ, â˜ƒ);
  ```

**Comment by XiaoPangxie732** [comment]
Which version you are using? If you are using 2.4, you could try 2.5. It fixed the --rvn bug, but the Spigot fork of FernFlower was removed since 2.5.
And no decompilers were called `SPIGOT`, all acceptable values could be found [here](https://github.com/MaxPixelStudios/MinecraftDecompiler/blob/e7ae3da5aeede219074ae6278a183c8e01d312db/src/main/java/cn/maxpixel/mcdecompiler/Info.java#L37-L40)
You could still use the Spigot fork of FernFlower through the user-defined decompiler.

**Comment by novastosha** [comment]
Sorry for the late response, I am using v2.4 because it's a release and I thought it would be more stable, even if I used "SPIGOT" are the decompilers produce bad code just like the one above but may be different (They produce the snowman emoji some times ☃️)

**Comment by novastosha** [comment]
By the way more glitches on ForgeFlower...

this is on "net.minecraft.network.PacketDecoder"

```java
   protected void decode(ChannelHandlerContext param1, ByteBuf param2, List<Object> param3) throws Exception {
      // $FF: Couldn't be decompiled
   }
```

**Comment by novastosha** [comment]
Also, CFR does not work at all (broken) (Doesn't output anyhting)

**Comment by novastosha** [comment]
Fernflower, is broken and doesn't decompile properly (or at least with errors)

If you're going to talk about recourses, the process is running on my machine that has an "AMD Ryzen 5 5600x", and the process was also given 16GB of RAM so there is basically no way of failing due to recourses... 

```
TRACE:       Processing method a (Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/phys/BlockHitResult;)Lnet/minecraft/world/InteractionResult;
WARN:           Method a (Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/phys/BlockHitResult;)Lnet/minecraft/world/InteractionResult; couldn't be decompiled.
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.jetbrains.java.decompiler.util.ListStack.pop(ListStack.java:32)
        at org.jetbrains.java.decompiler.util.ListStack.pop(ListStack.java:40)
        at org.jetbrains.java.decompiler.code.interpreter.InstructionImpact.processSpecialInstructions(InstructionImpact.java:468)
        at org.jetbrains.java.decompiler.code.interpreter.InstructionImpact.stepTypes(InstructionImpact.java:362)
        at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:688)
        at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:710)
        at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:710)
        at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsrInstructions(ControlFlowGraph.java:710)
        at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.removeJsr(ControlFlowGraph.java:672)
        at org.jetbrains.java.decompiler.code.cfg.ControlFlowGraph.inlineJsr(ControlFlowGraph.java:101)
        at org.jetbrains.java.decompiler.main.rels.MethodProcessorRunnable.codeToJava(MethodProcessorRunnable.java:76)
        at org.jetbrains.java.decompiler.main.rels.ClassWrapper.init(ClassWrapper.java:62)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.initWrappers(ClassesProcessor.java:369)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:316)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:114)
        at org.jetbrains.java.decompiler.struct.ContextUnit.save(ContextUnit.java:100)
        at org.jetbrains.java.decompiler.struct.StructContext.saveContext(StructContext.java:58)
        at org.jetbrains.java.decompiler.main.Fernflower.decompileContext(Fernflower.java:87)
        at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.decompileContext(ConsoleDecompiler.java:120)
        at cn.maxpixel.mcdecompiler.decompiler.FernFlowerDecompiler.decompile(FernFlowerDecompiler.java:71)
        at cn.maxpixel.mcdecompiler.MinecraftDecompiler.decompile0(MinecraftDecompiler.java:144)
        at cn.maxpixel.mcdecompiler.MinecraftDecompiler.decompile(MinecraftDecompiler.java:116)
        at cn.maxpixel.mcdecompiler.MinecraftDecompilerCommandLine.main(MinecraftDecompilerCommandLine.java:139)
```

**Comment by XiaoPangxie732** [comment]
My bad. I haven't tested the decompilers for some time. I'll check it later and fix it before next week.

**Comment by novastosha** [comment]
Don't sweat it but man make sure it works before publishing a release...

**Comment by XiaoPangxie732** [comment]
I pushed a commit that should fix this. You can download it after CI is passed and test it.

**Comment by XiaoPangxie732** [comment]
> and when using the "--rvn" option, referencing the the class it self using "this" doesn't work,

This is solved in #22.

**Comment by XiaoPangxie732** [comment]
> I hope you get better decompilers added very soon.

You can always use your favorite decompilers and arguments by configuring the user-defined decompiler.
I wrote some simple tutorials about this at [here](https://github.com/MaxPixelStudios/MinecraftDecompiler/wiki/Creating-a-User-Defined-Decompiler) and [here](https://github.com/MaxPixelStudios/MinecraftDecompiler/blob/master/decompiler/decompiler.properties). If anything is confusing you, you could ask me for help.

**Comment by XiaoPangxie732** [comment]
This issue should have been fixed completely. Thanks for reporting it!
